import { useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Image,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { StatusBar } from 'expo-status-bar';
import { analyzePosture } from './lib/analyzePosture';
import { compressImage } from './lib/compressImage';
import { Exercise, getTopExercises } from './lib/exerciseLibrary';
import { AnalysisStatus, PostureResult } from './types';

function ExerciseCard({ exercise, label }: { exercise: Exercise; label: string }) {
  const { start, end } = exercise.images ?? {};
  return (
    <View style={ex.card}>
      <Text style={ex.label}>{label}</Text>
      <Text style={ex.name}>{exercise.name}</Text>
      <Text style={ex.meta}>{exercise.sets_reps}</Text>
      {(start || end) && (
        <View style={ex.imageRow}>
          {start && (
            <View style={ex.imageWrap}>
              <Image source={start} style={ex.image} resizeMode="cover" />
              <Text style={ex.imageCaption}>Start</Text>
            </View>
          )}
          {end && (
            <View style={ex.imageWrap}>
              <Image source={end} style={ex.image} resizeMode="cover" />
              <Text style={ex.imageCaption}>End</Text>
            </View>
          )}
        </View>
      )}
      <Text style={ex.instructions}>{exercise.instructions}</Text>
      <View style={ex.benefitRow}>
        <Text style={ex.benefitTag}>Surf benefit: </Text>
        <Text style={ex.benefitText}>{exercise.surf_benefit}</Text>
      </View>
    </View>
  );
}

function ExerciseSection({ restrictions }: { restrictions: string[] }) {
  const exercises = getTopExercises(restrictions);
  if (exercises.length === 0) return null;

  return (
    <View>
      <Text style={styles.sectionTitle}>Your Top {exercises.length} Exercise{exercises.length !== 1 ? 's' : ''}</Text>
      {exercises.map((exercise, i) => (
        <ExerciseCard
          key={exercise.id}
          exercise={exercise}
          label={i === 0 ? 'Fix this first — biggest impact on your surfing' : 'Also add this to your routine'}
        />
      ))}
      <View style={ex.disclaimer}>
        <Text style={ex.disclaimerText}>
          ⚠️ Important: This analysis is generated by AI and may contain inaccuracies. It is not
          medical advice. Perform all exercises at your own risk. If you have any existing injuries,
          health conditions, or concerns, consult a qualified medical professional before starting
          any exercise program.
        </Text>
      </View>
    </View>
  );
}

function PoseGuide() {
  return (
    <View style={guide.box}>
      <Text style={guide.title}>How to take your photo</Text>

      {/* Stick figure in deep squat */}
      <View style={guide.figureWrap}>
        <Text style={guide.figure}>{'  O\n /|\\\n/ | \\\n|   |'}</Text>
        <View style={guide.frameRect}>
          <Text style={guide.frameLabel}>full body in frame</Text>
        </View>
      </View>

      <View style={guide.steps}>
        <Text style={guide.step}>1. Set your phone up at chest height, leaning against something stable</Text>
        <Text style={guide.step}>2. Stand facing the camera, feet shoulder-width apart</Text>
        <Text style={guide.step}>3. Squat as deep as you can — don't force it</Text>
        <Text style={guide.step}>4. Hold for 3 seconds, then snap the photo</Text>
        <Text style={guide.note}>Make sure your whole body fits — head to toes.</Text>
      </View>
    </View>
  );
}

export default function App() {
  const [imageUri, setImageUri] = useState<string | null>(null);
  const [status, setStatus] = useState<AnalysisStatus>('idle');
  const [result, setResult] = useState<PostureResult | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  async function pickImage() {
    const permission = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) {
      Alert.alert('Permission needed', 'Allow photo library access to pick a pose photo.');
      return;
    }
    const picked = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      quality: 1,
    });
    if (picked.canceled || !picked.assets[0]) return;

    const asset = picked.assets[0];
    setImageUri(asset.uri);
    setResult(null);
    setErrorMsg(null);
    setStatus('loading');

    try {
      const compressed = await compressImage(asset.uri, asset.width, asset.height);
      const analysis = await analyzePosture(compressed.base64, compressed.mimeType);
      setResult(analysis);
      setStatus('success');
    } catch (e) {
      setErrorMsg(e instanceof Error ? e.message : 'Unknown error');
      setStatus('error');
    }
  }

  const severityColor: Record<string, string> = {
    low: '#2ecc71',
    moderate: '#f39c12',
    high: '#e74c3c',
  };

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <StatusBar style="auto" />
      <Text style={styles.title}>SurfReady</Text>

      {!imageUri && <PoseGuide />}

      <Pressable style={styles.button} onPress={pickImage} disabled={status === 'loading'}>
        <Text style={styles.buttonText}>
          {imageUri ? 'Pick a different photo' : 'Take / pick a squat photo'}
        </Text>
      </Pressable>

      {imageUri && (
        <Image source={{ uri: imageUri }} style={styles.preview} resizeMode="contain" />
      )}

      {status === 'loading' && (
        <View style={styles.loadingBox}>
          <ActivityIndicator size="large" color="#0077b6" />
          <Text style={styles.loadingText}>Analyzing your pose…</Text>
        </View>
      )}

      {status === 'error' && (
        <Text style={styles.errorText}>{errorMsg}</Text>
      )}

      {status === 'success' && result && (
        <View style={styles.resultBox}>
          <Text style={styles.sectionTitle}>Summary</Text>
          <Text style={styles.body}>{result.summary}</Text>

          <Text style={styles.sectionTitle}>Restrictions Found</Text>
          {result.restrictions.map((r, i) => (
            <View key={i} style={styles.restrictionRow}>
              <Text style={[styles.severity, { color: severityColor[r.severity] }]}>
                [{r.severity.toUpperCase()}]
              </Text>
              <Text style={styles.area}> {r.area}</Text>
              <Text style={styles.observation}>{r.observation}</Text>
            </View>
          ))}

          <Text style={styles.sectionTitle}>Surf Impact</Text>
          <Text style={styles.body}>{result.surfRelevance}</Text>

          <Text style={styles.sectionTitle}>Focus First</Text>
          <Text style={[styles.body, styles.focusText]}>{result.suggestedFocus}</Text>

          <ExerciseSection restrictions={result.restrictions.map(r => r.area)} />
        </View>
      )}
    </ScrollView>
  );
}

const guide = StyleSheet.create({
  box: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#d0e8f5',
  },
  title: { fontSize: 16, fontWeight: '700', color: '#0077b6', marginBottom: 14, textAlign: 'center' },
  figureWrap: { alignItems: 'center', marginBottom: 14 },
  figure: {
    fontFamily: 'Courier',
    fontSize: 22,
    lineHeight: 28,
    color: '#0077b6',
    textAlign: 'center',
    marginBottom: 6,
  },
  frameRect: {
    borderWidth: 2,
    borderColor: '#aaa',
    borderStyle: 'dashed',
    borderRadius: 6,
    paddingHorizontal: 24,
    paddingVertical: 4,
    marginTop: 4,
  },
  frameLabel: { fontSize: 11, color: '#888', textAlign: 'center' },
  steps: { gap: 8 },
  step: { fontSize: 14, color: '#333', lineHeight: 20 },
  note: { fontSize: 13, color: '#0077b6', fontWeight: '600', marginTop: 4 },
});

const styles = StyleSheet.create({
  container: { flexGrow: 1, padding: 20, backgroundColor: '#f0f4f8', alignItems: 'center' },
  title: { fontSize: 24, fontWeight: '700', marginTop: 60, marginBottom: 24, color: '#0077b6' },
  button: {
    backgroundColor: '#0077b6',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 10,
    marginBottom: 20,
  },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  preview: { width: 300, height: 300, borderRadius: 10, marginBottom: 20 },
  loadingBox: { alignItems: 'center', marginTop: 20 },
  loadingText: { marginTop: 10, color: '#555', fontSize: 15 },
  errorText: { color: '#e74c3c', marginTop: 16, textAlign: 'center', fontSize: 14 },
  resultBox: { width: '100%', marginTop: 12 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0077b6',
    marginTop: 18,
    marginBottom: 6,
  },
  body: { fontSize: 14, color: '#333', lineHeight: 21 },
  restrictionRow: { marginBottom: 12 },
  severity: { fontWeight: '700', fontSize: 13 },
  area: { fontWeight: '600', fontSize: 14, color: '#222' },
  observation: { fontSize: 13, color: '#555', marginTop: 2, lineHeight: 19 },
  focusText: { fontWeight: '600', color: '#0077b6' },
});

const ex = StyleSheet.create({
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#d0e8f5',
  },
  label: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0077b6',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  name: { fontSize: 16, fontWeight: '700', color: '#1a1a2e', marginBottom: 4 },
  meta: { fontSize: 12, color: '#888', marginBottom: 8 },
  imageRow: { flexDirection: 'row', gap: 10, marginBottom: 12, justifyContent: 'center' },
  imageWrap: { alignItems: 'center' },
  image: { width: 120, height: 150, borderRadius: 12 },
  imageCaption: { fontSize: 11, color: '#888', marginTop: 4, textTransform: 'uppercase', letterSpacing: 0.5 },
  instructions: { fontSize: 14, color: '#333', lineHeight: 21, marginBottom: 10 },
  benefitRow: { flexDirection: 'row', flexWrap: 'wrap' },
  benefitTag: { fontSize: 13, fontWeight: '700', color: '#0077b6' },
  benefitText: { fontSize: 13, color: '#555', flex: 1 },
  disclaimer: {
    marginTop: 16,
    backgroundColor: '#fff8e1',
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: '#ffe082',
  },
  disclaimerText: { fontSize: 12, color: '#5d4037', lineHeight: 18 },
});
